//
// Created by Ifeanyi Oraelosi on 20.02.22.
//

#ifndef STAGING_CLION_C_STAGING_CLION_SRC_PRACTICE_EMPLOYEE_H
#define STAGING_CLION_C_STAGING_CLION_SRC_PRACTICE_EMPLOYEE_H

class Employee {

};

#endif //STAGING_CLION_C_STAGING_CLION_SRC_PRACTICE_EMPLOYEE_H
